### PR TITLE
Submit TTwof

### PR DESCRIPTION
**Pull request by EljoDev**
Submission of the ttwof dapp.

### CODE REVIEW

**Comment by Felix0xTHUNDER** [comment]
gn, the team will help to review this PR

**Comment by Felix0xTHUNDER** [comment]
Please update the contract on dappradar as well, thanks.

**Comment by EljoDev** [comment]
Yes I will do it obviously but I can't for the moment

**Comment by EljoDev** [comment]
Done

**Comment by Felix0xTHUNDER** [comment]
please update the contract to the correct one, thanks.

**Comment by Felix0xTHUNDER** [comment]
This PR doesn't meet the listing requirements so i close the PR.

**Pull request closed without merging**
