### PR TITLE
init TTPrize

### PR DESCRIPTION
**Pull request by logicofgod**
TTPrize is the game gives great Rewards for both winners and losers.

### CODE REVIEW

**Comment by Felix0xTHUNDER** [comment]
The image on the webview is a bit compressed, could you adjust that?
Thanks.

**Comment by Felix0xTHUNDER** [comment]
HI, @logicofgod could you add more win / lose introductions in this DApp?
Thanks.

**Comment by logicofgod** [comment]
We already fixed the webview issue and added the rules into score table.

**Comment by Felix0xTHUNDER** [comment]
Thanks, the team will proceed this PR.
@logicofgod please check your email.

**Comment by Felix0xTHUNDER** [comment]
I just match 3 but only get 4 TT back, please check the mechanism or change the rule.

I didn't get Prize Tokens when I lose.

We suggest that you can add the Prize token distribution every round and the users' balance.

Or even the swap button so that users can easily swap anything.

**Comment by logicofgod** [comment]
We fixed match3 issue and added Prize balance to the user interface.
Thanks your suggestion.

**Comment by Felix0xTHUNDER** [comment]
thanks, the team will proceed.

**Comment by Felix0xTHUNDER** [comment]
@logicofgod 
Now it shows "?" prize balance if you don't have any.
Is there any possibility to show the real amount?

**Comment by logicofgod** [comment]
If there is no wallet connection, it will display ? Prize.
If wallet connected,it will display the real Prize amount.

**Comment by Felix0xTHUNDER** [comment]
We suggest that you can add more details at the playing result.
Like "you matched 4 numbers. Win XXX TT"
or "you only matched 2 numbers, get XXX Prize.
Thanks.

**Comment by logicofgod** [comment]
done
image
image

**Comment by Felix0xTHUNDER** [comment]
Have you already submitted for listing on dappradar?

**Comment by logicofgod** [comment]
https://dappradar.com/thundercore/gambling/tt-prize
already listed

**Comment by Felix0xTHUNDER** [comment]
Got it, thanks

**Review by Felix0xTHUNDER — APPROVED** [review]

**Review by Maneshjl — APPROVED** [review]
LGTM

**Pull request merged**
