### PR TITLE
TT-Baccarat

### PR DESCRIPTION
**Pull request by hazardland**

### CODE REVIEW

**Comment by Maneshjl** [comment]
Looks good to me

**Review by Maneshjl — APPROVED** [review]
LGTM

**Review by Felix0xTHUNDER — APPROVED** [review]

**Comment by Michris1** [comment]
Still check out http://flip.ttflash.online

**Comment by hazardland** [comment]
@Michris1 you mean we should do a coin flip game in our style?

**Comment by Michris1** [comment]
> @Michris1 you mean we should do a coin flip game in our style?

That would be great 😃. But I made that, am still trying to get it approved on tthub.

**Pull request merged**
