### PR TITLE
Add new Game Planet Knight

### PR DESCRIPTION
**Pull request by diceplanet**
also add our telegram group

### CODE REVIEW

**Comment by ragnarok1993** [comment]
Tendra un token este juego nativo

**Comment by Felix0xTHUNDER** [comment]
gm @diceplanet 
I found that the dapp can't automatically read my wallet balance unless i click on $TT or $PMT
Please help to check :D

**Comment by diceplanet** [comment]
Thank you for sharing the issue with us.
But, we've checked the balance item. Maybe there exists some time delay,
could you try again?
Many thanks!!

felix-thundercore ***@***.***> 於 2022年11月8日週二 下午5:46寫道：

**Comment by Felix0xTHUNDER** [comment]
okay got it. 
The team will help to process.

**Comment by diceplanet** [comment]
Dear Thundercore team,

Thank you, we confirm that the problem has been resolved.

Please assist!

**Comment by Felix0xTHUNDER** [comment]
Cool, LFG :D

**Comment by Felix0xTHUNDER** [comment]
image
Still the same, but after I played 1 round, the balance appears.

image

**Comment by diceplanet** [comment]
Dear Thundercore team,

Sorry, we deeply apologized.

Our team checked interfaces both mobile and desktop.

The images you showed. We confirmed the issue  came from desktop version.

However, the mobile version is fine.

The problem has been resolved. Please checked.

Thank you,

**Comment by Felix0xTHUNDER** [comment]
Got it, thanks!!

**Comment by diceplanet** [comment]
Thank you! Please assist !

**Comment by Felix0xTHUNDER** [comment]
thanks, 🐸

**Review by Felix0xTHUNDER — APPROVED** [review]

**Review by Maneshjl — APPROVED** [review]
looks good to me

**Pull request merged**
