### PR TITLE
Fun Bird by TFN Listing Request

### PR DESCRIPTION
**Pull request by tfunfun22**

### CODE REVIEW

**Comment by Felix0xTHUNDER** [comment]
The team will help to review listing

**Comment by Felix0xTHUNDER** [comment]
Hi devs, can you improve the popup issue? 
And our team will help to review the PR, thanks.

**Comment by tfunfun22** [comment]
> Hi devs, can you improve the popup issue?

@Felix0xTHUNDER , can you explain me the detail about popup issue?

**Comment by Felix0xTHUNDER** [comment]
@tfunfun22 When I enter to the website, will be asked to connect the wallet or I can't do anything,
Can this step be removed? So that users can view the website first.

**Comment by tfunfun22** [comment]
> @tfunfun22 When I enter to the website, will be asked to connect the wallet or I can't do anything, Can this step be removed? So that users can view the website first.

Hi @Felix0xTHUNDER i already fixed wallet connection step

**Comment by Felix0xTHUNDER** [comment]
Thanks, team will continue the listing process.

**Comment by vandoe** [comment]
> Thanks, team will continue the listing process.

When approve sir

**Comment by Felix0xTHUNDER** [comment]
@tfunfun22 please update the twitter link on the website and add "twitter" to the PR as well.
Thanks, the team will proceed to list.

**Comment by tfunfun22** [comment]
> @tfunfun22 please update the twitter link on the website and add "twitter" to the PR as well. Thanks, the team will proceed to list.

@Felix0xTHUNDER Done

**Comment by Felix0xTHUNDER** [comment]
**"Build fun bird game one on one player"**

Have you already finished this?
If yes please help to update the roadmap.

**Review by Felix0xTHUNDER — APPROVED** [review]

**Review by Maneshjl — APPROVED** [review]
Looks good to me

**Comment by vandoe** [comment]
Good job @Felix0xTHUNDER

**Pull request merged**
