### PR TITLE
init

### PR DESCRIPTION
**Pull request by samuelysliu**
Dapp Submission: Three Star Game

### CODE REVIEW

**Comment by Felix0xTHUNDER** [comment]
@smauelbarry gn,
Black screen if you dont connect with wallet.
Can you fix it? thanks.

**Comment by samuelysliu** [comment]
> @smauelbarry gn, Black screen if you dont connect with wallet. Can you fix it? thanks.

I fixed it, thank you for checking.

**Comment by Felix0xTHUNDER** [comment]
Thanks, the team will process this application.

**Comment by samuelysliu** [comment]
> Thanks, the team will process this application.

@Felix0xTHUNDER Hello, may I ask how long it will take for process this application ? thanks

**Pull request closed without merging**
