### PR TITLE
Add Shell

### PR DESCRIPTION
**Pull request by LucienSong**
Add shell.org DAPP

### CODE REVIEW

**Comment by Felix0xTHUNDER** [comment]
Thanks for your application, could you help to put the social link in a more conspicuous place?

**Comment by LucienSong** [comment]
> 
Thanks for review.
I have added the social link to the top of the index page.
screen
.

**Comment by Felix0xTHUNDER** [comment]
Hi team @LucienSong ,
Everything is fine,
But there is one issue, 
We recommend that you can change to open it in the same page in the place of ""bridge & swap""
So that TT Swap can be successfully opened in the webview of TT Wallet and brought in your token address.

We suggest you can delete [target="_blank"].
`<a href="[TTSwap | Dex on ThunderCore](https://ttswap.space/#/swap/0x05db20427bbce9f356422db8ca65097b11fbaff8%22)  **target="_blank"** class="text-grey-5 text-subtitle2 text-mono" data-v-6a1bab5e="">Bridge & Swap</a>`

**Comment by LucienSong** [comment]
> 
Hi, @Felix0xTHUNDER 
Thanks for your suggestion.
We have updated the swap button.

**Comment by Felix0xTHUNDER** [comment]
Thanks, the team will proceed for listing.

**Review by Maneshjl — APPROVED** [review]
looks good to me

**Review by Felix0xTHUNDER — APPROVED** [review]

**Pull request merged**
