### PR TITLE
Thunder Manager

### PR DESCRIPTION
**Pull request by TrevorBanco**

### CODE REVIEW

**Comment by rogerhsu-dev** [comment]
https://thundermanager.com is not available at this moment.

**Comment by TrevorBanco** [comment]
Already paid, just waiting on ownership transfer, should be within the week.

**Comment by TrevorBanco** [comment]
Server started, should be viewable, may take few hours. How long will it take & where do I see this app store?

**Comment by Felix0xTHUNDER** [comment]
Please update the following:

1.Leave "slug" ,"email", "twitter", "discord" blank if you don't have one.
2.Add your community's telegram link under "telegram".
3.Update the "categories" to "DeFi".
4.Provide a more relevant "description" that helps users understand your DApp.
5.Add contract addresses for your DApp.

**Comment by rogerhsu-dev** [comment]
> Server started, should be viewable, may take few hours. How long will it take & where do I see this app store?

The app list is for https://dapps.thundercore.com/#/ and the home tab of ThunderCore Hub.

**Review by Maneshjl — APPROVED** [review]
Looks good to me

**Review by Felix0xTHUNDER — APPROVED** [review]

**Pull request merged**
