### PR TITLE
add zootopia

### PR DESCRIPTION
**Pull request by htag3782**
Zootopia is a DeFi product

### CODE REVIEW

**Comment by Felix0xTHUNDER** [comment]
Hi dves, 
Would you like to create the community?

**Comment by htag3782** [comment]
@Felix0xTHUNDER I'd love to run a community, but it's have to see if the product has a good response on thundercore.

**Comment by Felix0xTHUNDER** [comment]
Got it, the team will proceed the review.
BUt we suggest that you can start to operate the community.

**Review by rogerhsu-dev — CHANGES_REQUESTED** [review]
Please remove .idea related files in PR

**Comment by htag3782** [comment]
@rogerhsu-tt ok I removed it, thanks

**Comment by vandoe** [comment]
Screenshot_20220818-121836_TT Wallet
Nice
@PanduSwastika83

**Comment by vandoe** [comment]
> Zootopia is a DeFi product

Screenshot_20220828-122309_TT Wallet
followers have reached 52. when will the winner be announced?

**Comment by htag3782** [comment]
@vandoe check this
https://twitter.com/Zootopia_defi/status/1567344575441944578?s=20&t=oNXB8_L-5ym9fXE43MLUaQ

**Comment by vandoe** [comment]
> @vandoe check this https://twitter.com/Zootopia_defi/status/1567344575441944578?s=20&t=oNXB8_L-5ym9fXE43MLUaQ

Nice

**Comment by Felix0xTHUNDER** [comment]
The dev left invalid mail and the DApp is not eligible for listing. The team will close the PR.

**Pull request closed without merging**
