### PR TITLE
Dapp Listing Request

### PR DESCRIPTION
**Pull request by bitdoggy**
The BitDoggys are an art collection for an NFT staking project built within the Thundercore and Cronos network, a BitDoggy is a character that is part of an 7777 algorithmically generated collection consisting of extremely unique features. Each item can be staked on the BitDoggy vault to receive BitDoggy Token (BDT) rewards.

### CODE REVIEW

**Comment by Gmtenchi777** [comment]
Put your dapp description and prepare coin listing

**Comment by Gmtenchi777** [comment]
Wait for the thundercore team to evaluate

**Comment by Gmtenchi777** [comment]
@Felix0xTHUNDER @Maneshjl rate this

**Comment by Gmtenchi777** [comment]
Twitter ok
Telegram group ok
Discord ok
Link site dapp ok
What's left for him to list

**Comment by Gmtenchi777** [comment]
@rogerhsu-tt @Felix0xTHUNDER @hazardland

**Comment by Felix0xTHUNDER** [comment]
Thanks for the reminder, the team has been working on it.

**Comment by Felix0xTHUNDER** [comment]
checking with the dev for the NFT display issue

**Review by Gmtenchi777 — COMMENTED** [review]
Fix nfts bug not showing up in TT hub wallet . And on the Stack page

**Comment by Felix0xTHUNDER** [comment]
@bitdoggy gm dev, please check dm on tg :D Thanks!

**Comment by Felix0xTHUNDER** [comment]
This project did not pass the listing requirements. @bitdoggy, please fix the NFT metadata and check the dm. Thanks!

**Pull request closed without merging**
