### PR TITLE
Adding PokerDice project

### PR DESCRIPTION
**Pull request by dhasan**
Adding PokerDice project

### CODE REVIEW

**Comment by Felix0xTHUNDER** [comment]
Thanks for the submission, the team will help to review : D

**Comment by Gmtenchi777** [comment]
you will create a dividend coin or not and a telegram group

**Comment by dhasan** [comment]
> you will create a dividend coin or not and a telegram group

As of now dividend token won't be created, In the future probably yes, with the second version of contract depending on the interest to the games.
Telegram channel has been created and added to this PR.
Thanks.

**Comment by Gmtenchi777** [comment]
Ok bro

**Comment by Gmtenchi777** [comment]
You created a Telegram channel and not a group

**Comment by Gmtenchi777** [comment]
Creating a group we filled with investors

**Comment by Gmtenchi777** [comment]
So your project will have more vision, also try to put it on the radar dapp

**Comment by dhasan** [comment]
Thanks for the information, telegram group added. 
Dapp already listed on dappradar https://dappradar.com/thundercore/gambling/pokerdice
Thanks

**Comment by Gmtenchi777** [comment]
A add something that shows our balance

**Comment by dhasan** [comment]
> A add something that shows our balance

It is Done.
Thanks.

**Comment by dhasan** [comment]
Thank you @Felix0xTHUNDER 
Is there anything else that I can do? Please let me know.

**Comment by dhasan** [comment]
Divided token and exchange created 

https://viewblock.io/thundercore/address/0x54709eba537955a9be4f5014abffb528c0879071

https://viewblock.io/thundercore/address/0xdb0cd28283663f5740425332580b8b45bca4f829

**Comment by dhasan** [comment]
Staking page and contract are under development at the moment, once we finish with those I will publish them under subdomain of ethgames.fun , and will create PR for token listing @Gmtenchi777 FYI

**Comment by Gmtenchi777** [comment]
@Felix0xTHUNDER I heard what he said I sent your contact for you to explain to him on Telegram about the listings his liquidity is good

**Review by Gmtenchi777 — COMMENTED** [review]
It's getting good keep up the good work In creating the dividends.And make your games more attractive every day and so the value of the coin can rise more

**Comment by Felix0xTHUNDER** [comment]
Got it, thanks for the description.  
The team will help to review and process the listing if it's suitable to list.

**Comment by dhasan** [comment]
Thank you @Felix0xTHUNDER 
I will be happy to get some feedback, and settle concerns if any.

**Review by Gmtenchi777 — COMMENTED** [review]
this is a good sign your project is improving .then just list your coins and start dividends

**Comment by dhasan** [comment]
Dividends Dapp listing PR https://github.com/thundercore/ecosystem/pull/77

**Review by Gmtenchi777 — COMMENTED** [review]
Check this @Felix0xTHUNDER @Maneshjl @rogerhsu-tt

**Comment by dhasan** [comment]
If this blockchain is created for the purpose of earning money of a small group of people from gambling games somehow connected to admins, receiving cuts or payroll from them just say it and don’t waste our time and money, otherwise I don’t understand this stubbornness

**Pull request closed without merging**
