### PR TITLE
Add AgeOfDefi ⚡

### PR DESCRIPTION
**Pull request by zeus-tt**
https://zeusswap.fi/

### CODE REVIEW

**Comment by Felix0xTHUNDER** [comment]
Thanks for the application, the team will help to review this PR. 🙏

**Comment by Felix0xTHUNDER** [comment]
Doc link is invalid, please help to fix that.

**Comment by Maneshjl** [comment]
@zeus-tt please follow through on updating the doc links as mentioned by Felix so we may continue with your listing application.

**Comment by Felix0xTHUNDER** [comment]
Closing PR due to inactivity from project owner

**Pull request closed without merging**
