### PR TITLE
submit TT3Star

### PR DESCRIPTION
**Pull request by sasakevin**

### CODE REVIEW

**Comment by vandoe** [comment]
Screenshot_20220816-081839_TT Wallet

no dividend claim appears on GMT 08/16 00:00

**Comment by vandoe** [comment]
Screenshot_20220816-082149_TT Wallet

no dividend claim appears on GMT 08/16 00:00

**Comment by Felix0xTHUNDER** [comment]
@sasakevin gm, could you please check @vandoe issue?
Thanks.

**Comment by vandoe** [comment]
> @sasakevin gm, could you please check @vandoe issue? Thanks.

I can't claim dividends at GMT 08/16 00.00, because the claim dividend button doesn't appear

**Comment by sasakevin** [comment]
@Felix0xTHUNDER  @vandoe sorry, my dividends contract had some error, I just fixed now.
Thanks for checked.

**Comment by vandoe** [comment]
> @Felix0xTHUNDER @vandoe sorry, my dividends contract had some error, I just fixed now. Thanks for checked.

Screenshot_20220816-115126_TT Wallet
my total stake is gone

**Comment by vandoe** [comment]
This is my wallet 0xa7f6dafefdc55122f2218a8030be12f2fa996bee

**Comment by Gmtenchi777** [comment]
My  6.40 stars disappears check wallet 0xdbe2c9eff4c14fdef3fea3104e7090daeaa5c30a

**Comment by sasakevin** [comment]
@vandoe @Gmtenchi777 Sorry for the error in my smart contract, I upload a new contract(and address renewed), so the past balance disappeared. I sended 10 3 Stars token to both of you for testing, thank you.

**Comment by vandoe** [comment]
> @vandoe @Gmtenchi777 Sorry for the error in my smart contract, I upload a new contract(and address renewed), so the past balance disappeared. I sended 10 3 Stars token to both of you for testing, thank you.

Ok thanks

**Comment by sasakevin** [comment]
@vindy1995
https://viewblock.io/thundercore/address/0x5b2afc9c6b9eef8300b916ac539bed5946b6b29b
 According to Block explorer I don't see this address has stake 3Star token.
Can you describe the process of disappearing?

**Comment by xandaopizzas** [comment]
hello dev. I put the 3star coins in the stack, when I went to claim the day they disappeared, I'll send you the wallet to see what you can do for me, I don't remember how many they were, I know I bet more than a thousand tts on them in the game

tt wallet:  0xa342746a7c428595cd0887aa75183422743734f9

the 3 and 4 star

**Comment by vindy1995** [comment]
> @vindy1995 https://viewblock.io/thundercore/address/0x5b2afc9c6b9eef8300b916ac539bed5946b6b29b According to Block explorer I don't see this address has stake 3Star token. Can you describe the process of disappearing?

**Comment by vindy1995** [comment]
>

**Comment by vindy1995** [comment]
> @vindy1995 https://viewblock.io/thundercore/address/0x5b2afc9c6b9eef8300b916ac539bed5946b6b29b According to Block explorer I don't see this address has stake 3Star token. Can you describe the process of disappearing?

Screenshot_2022-08-17-23-42-38-725_com android chrome

Cek i stake all 3stars and now my stake 0

**Comment by Gmtenchi777** [comment]
Ok bro

**Comment by sasakevin** [comment]
@xandaopizzas @vindy1995 hi, I checked the address records from two days ago that were sent to the old contract by 3star, and yesterday I updated the new contract. So the staked in the past cannot be seen.

image


I sended 10 3 stars for you two to test it.

New contract address: 0x5B2AFc9c6b9eef8300B916aC539bED5946B6b29B
Old contract address: 0xa931A981edfCd9cA80A0Be1653CE3b1C4ceb757e(Abandon)

**Comment by Gmtenchi777** [comment]
hi sasa kevin creates a group on Telegram and twitter

**Comment by Gmtenchi777** [comment]
Add more liquidity

**Comment by Gmtenchi777** [comment]
So new players saw

**Review by Gmtenchi777 — COMMENTED** [review]
Create a Telegram group and a twitter page and I'll do the marketing xd I'm from a group from Brazil we have 380 members who love TT games and dividends

**Comment by xandaopizzas** [comment]
> @xandaopizzas @vindy1995oi, verifiquei os registros de endereço de dois dias atrás que foram enviados para o contrato antigo pela 3star e ontem atualizei o novo contrato. Assim, o apostado no passado não pode ser visto.
> 
> imagem
> 
> Enviei 10 3 estrelas para vocês dois testarem.
> 
> Novo endereço do contrato: 0x5B2AFc9c6b9eef8300B916aC539bED5946B6b29B Endereço do antigo contrato: 0xa931A981edfCd9cA80A0Be1653CE3b1C4ceb757e(Abandon)

Quando foi adicionado as moedas

**Comment by xandaopizzas** [comment]
Hi Dev.  I'm now riding the 10 3star that I had to send to my wallet
0xa342746a7c428595cd0887aa75183422743734f9

**Comment by Baronete1982** [comment]
Hi,
My 3star coins disappeared from the stake!

0x056b2ecf3385f16bc8d9878181ae7f341ff5cd61

1,5     3star or more

**Comment by sasakevin** [comment]
@Gmtenchi777 OK I will create Telegram and twitter, thanks

**Comment by sasakevin** [comment]
@xandaopizzas sorry, could you speak English?

**Comment by sasakevin** [comment]
@Baronete1982 Hi, I found out that your 1.5 3Star was staked to the old contract two days ago, and the contract was updated yesterday.
https://user-images.githubusercontent.com/110898392/185284708-02731363-1949-497a-9cf5-692c295971b8.png

**Comment by Gmtenchi777** [comment]
https://t.me/ThunderCoreFarms

Join my group and send the link of your created group and admin me

**Comment by Gmtenchi777** [comment]
Telegram won't let me write in groups I'm not admin

**Comment by vindy1995** [comment]
> @xandaopizzas @vindy1995 hi, I checked the address records from two days ago that were sent to the old contract by 3star, and yesterday I updated the new contract. So the staked in the past cannot be seen.
> 
> image
> 
> I sended 10 3 stars for you two to test it.
> 
> New contract address: 0x5B2AFc9c6b9eef8300B916aC539bED5946B6b29B Old contract address: 0xa931A981edfCd9cA80A0Be1653CE3b1C4ceb757e(Abandon)

My 3stars 0 now
When you give 10 3stars?

**Comment by Baronete1982** [comment]
> 

Thanks

**Comment by sasakevin** [comment]
@vindy1995 I founded you stake 3.76 3star, I will return it, sorry.

**Comment by Alcirsantana** [comment]
hello dev my 3star in stake disappeared could check for me goes there my wallet thundercore
0x354c359862facaccc72bac728eead83e50fb4679

**Comment by Alcirsantana** [comment]
hello dev my 3star in stake disappeared could check for me goes there my wallet thundercore
0x354c359862facaccc72bac728eead83e50fb4679

**Comment by sasakevin** [comment]
@Alcirsantana Hi,  I apologize for that inconvenience. I will return 1.84 token. And you can restaked it. thank you

**Comment by sasakevin** [comment]
@Gmtenchi777 I created twitter and telegram, thanks for suggestion.
twitter: https://twitter.com/3star_tt
telegram: https://t.me/+vxK3xKpQSoYyMjE5

**Comment by Gmtenchi777** [comment]
Telegram groups ok
Twitter ok
Dappradar ok
Join group thundercore oficial call ADM bubalex pra Roger hsu list you token 3 star

**Review by Gmtenchi777 — COMMENTED** [review]
Join thundercore Telegram group oficial
https://t.me/thunder_official
Add more liquidity and more coins TT swap

**Comment by Gmtenchi777** [comment]
What happened sasakevin that your telegram group disappeared

**Comment by sasakevin** [comment]
@Gmtenchi777 Sorry someone attack our telegram account, I will as soon as possiable figure out and recreated group

**Comment by Gmtenchi777** [comment]
Ok @sasakevin

**Comment by Gmtenchi777** [comment]
Bro add me whatsapp 55 12982870122 GM tenchi777

**Comment by Felix0xTHUNDER** [comment]
@sasakevin   Are all the issues solved?
You should create a telegram in the beginning. Seems here are too many texts. lol

**Comment by sasakevin** [comment]
@Felix0xTHUNDER Yes, all working.

**Review by Gmtenchi777 — COMMENTED** [review]
what happened bro Claim button doesn't work The coin has fallen in value Two wallets withdrew high value in TT that exceeds 400 dollars Everyone wants explanations bro we of something information

**Comment by sasakevin** [comment]
@Gmtenchi777 already fixed it

**Comment by Gmtenchi777** [comment]
New bugs were found how are you going to solve this Create new game and coin contract and give coins to stack people

**Comment by Gmtenchi777** [comment]
Can you explain to me how this hack was and why the wallet funds were transferred to another wallet

**Comment by Gmtenchi777** [comment]
0xED96B92a32809B71054d58B9a909F9B65a45Ca83

More than 80 thousand TT were transferred to this wallet

**Comment by Felix0xTHUNDER** [comment]
The winning numbers will not be displayed in the game, please help to fix that.
Thanks!

**Comment by sasakevin** [comment]
@Felix0xTHUNDER Hello Felix. The background color of the numbers will change to yellow only when there is a winning number in the player number. After testing, I don't have any bugs so far.
You mean for me to add a winning number display?

**Comment by Felix0xTHUNDER** [comment]
It will be great if you can add a winning number display. :D

**Comment by sasakevin** [comment]
The update is complete, please check it, thank you.

**Comment by Felix0xTHUNDER** [comment]
This PR doesn't meet the listing requirements so i close the PR.

**Pull request closed without merging**
